CLI Implementation
pitt-crc/Node-Nanny pull request #22
Opened 2022-06-15 13:52 UTC by Comeani

Using the base parser and parsing functionality contained in the wrapper scripts as a guide I've started my attempt at a CLI app for the usage monitor, with preliminary code for #3, #4 and #5. 

The first commit here is mostly to make sure that I'm not totally off track with anything, and I plan to make more changes before requesting formal review.

I haven't worked at all on layered applications before. Am I correct in using the execute method to wrap an instance of what our MonitorUtility ends up being (I guessed that will be similar to the "app_logic" sections of the wrapper scripts), instead of having that class be a child class to CLIParser? My thought was do all of the command line related thing here and just use MonitorUtility for following through on the ensuing logic.

2022-06-15 13:56 UTC, Comeani commented
Also, should this be moved from Node-Nanny/node_nanny/cli to Node-Nanny/cli?

2022-06-15 19:14 UTC, djperrefort commented
> Also, should this be moved from Node-Nanny/node_nanny/cli.py to Node-Nanny/cli.py?

No. The parsing logic is part of the application and should be bundled as such. The executable should call the CLI from within the application as a separate thing.

I think of this in terms of testability. Everything I may want to test goes in the package - which includes the parsing logic but not the executable.

2022-07-13 18:50 UTC, Comeani commented
I think this is in solid shape to start. I will need to make some tests and we'll probably end up making some changes to the individual argument definitions, but this can at least interface the executable to the correct command from MonitorUtility and reflects what we have in design doc.

2022-07-14 14:43 UTC, djperrefort requested changes
Looks solid so far. Most of my comments are very minor and can be addressed by running a linter.

2022-07-14 14:43 UTC, djperrefort commented on node_nanny/cli.py
> +            parser_class=ArgumentParser,
Should this be `parser_class=self.__class__`? That way subparsers share any custom behavior we implement (e.g., for error message handling).

2022-07-14 14:43 UTC, djperrefort commented on node_nanny/cli.py
> +        scan = command.add_parser(
Calling this subparser gives:

```python
Traceback (most recent call last):
  File "/home/djperrefort/Github/Node-Nanny/temp.py", line 4, in <module>
    CLIParser().execute()
  File "/home/djperrefort/Github/Node-Nanny/node_nanny/cli.py", line 210, in execute
    getattr(app,args.pop('command'))(**args)
AttributeError: 'MonitorUtility' object has no attribute 'scan'
```

I get similar errors for the `whitelist` and `history` parsers.

2022-07-14 14:43 UTC, djperrefort commented on node_nanny/cli.py
> +        # Print help when no arguements are provided
arguements -> arguments

2022-07-14 14:43 UTC, djperrefort commented on node_nanny/cli.py
> +    def error(self, message):
Pep8

2022-07-14 14:43 UTC, djperrefort commented on node_nanny/cli.py
> +        whitelist = command.add_parser(
This variable is unused. If there are no arguments to attach, then the assignment part of the line can be dropped.

2022-07-14 14:43 UTC, djperrefort commented on node_nanny/cli.py
> +        except KeyboardInterrupt:
This design decision was made for the wrapper scripts because they run non-python code with no guarantee the piped subprocess will work correctly. 

For this project, I'm not yet convinced the try/except statement is necessary.

2022-07-14 16:23 UTC, Comeani commented on node_nanny/cli.py
> +from node_nanny.app import MonitorUtility
I can't seem to get this one to show up in pylint. Is this referring to [this item on imports?](https://peps.python.org/pep-0008/#imports:~:text=Imports%20should%20be%20grouped%20in%20the%20following%20order%3A)

2022-07-14 20:52 UTC, djperrefort commented on node_nanny/cli.py
> +from node_nanny.app import MonitorUtility
Yah. I don't use pylint directly but rely on the PEP8 checker built into pycharm. The IDE keyboard shortcut for auto-formatting files to fix any formatting violations has become enough of a reflex that I hardly think about it anymore.

2022-07-14 20:56 UTC, Comeani commented on node_nanny/cli.py
> +        scan = command.add_parser(
This is only happening because `scan` is an allowed option for the command, but it has not yet been implemented in app.py. 

Here is the output when an invalid command is provided: 
```
./usage_monitor.py test
usage: usage_monitor.py [-h] {scan,kill,history,whitelist,add,remove} ...
usage_monitor.py: error: argument command: invalid choice: 'test' (choose from 'scan', 'kill', 'history', 'whitelist', 'add', 'remove')
```

2022-07-14 20:57 UTC, djperrefort commented on node_nanny/cli.py
> +            parser_class=ArgumentParser,
This made me realize there is a `*args` missing from the `__init__` signature (and from the super call).

2022-07-14 21:13 UTC, Comeani commented on node_nanny/cli.py
> +            parser_class=ArgumentParser,
My recent commits should address this, do I need to resolve all of the comments here or re-request review to allow you to start another one after you've submitted with requests for changes?

2022-07-15 15:06 UTC, djperrefort approved these changes

2022-07-15 15:06 UTC, djperrefort commented on node_nanny/cli.py
> +    def __init__(self, **kwargs) -> None:
Add `*args`

2022-07-15 15:06 UTC, djperrefort commented
One small comment. Otherwise LGTM.

2022-07-15 15:15 UTC, Comeani commented
Taking a look at #33, would it be better to have the CLI interface to that functionality look something like:

```
usage_monitor.py whitelist show ...
usage_monitor.py whitelist add ...
usage_monitor.py whitelist remove ...

```
I.e. nested subparsers for the whitelist command? 

Can always change that up in another PR later too I suppose if this one's good to merge.

2022-07-15 15:17 UTC, djperrefort commented
I vote to merge this for now. We can do a dedicated user interface review once the core functionality is there.

2022-07-20 15:23 UTC, merged